# Generated by Django 4.2.2 on 2023-07-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contacts_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=40)),
                ('teacher', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('max_student', models.IntegerField()),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
