# Generated by Django 4.2.2 on 2023-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='detail',
            field=models.CharField(default='', max_length=60),
        ),
    ]
